"""AI file-name summarizer for the Finder demo — "auto_awesome" toolbar button.

The button swaps the real file names in the current folder for short,
human-readable names generated by the LLM ("quarterly_budget_v3_FINAL.txt"
→ "Q3 budget report"). It reuses the chat panel's provider/model selection
(OpenCode / Cline / ZCode agent CLIs via md_llm), runs the files one by one —
the footer shows a linear progress bar filling file by file — and stores every
finished summary in ``~/.shangceng/filenames.json`` so the same work is never
repeated: on later runs only uncached (new or modified) files hit the LLM.

Only text-based formats are summarized (the app's TEXT_TYPES set decides);
images, videos and other binaries keep their real names. Records are keyed by
absolute path and invalidated when the file's mtime or size changes. Failed
runs are not cached, so the next run retries them.

Set ``SHANGCENG_HOME`` to move the cache folder somewhere else (tests do).
"""
from __future__ import annotations

import datetime as dt
import json
import os
import re
import threading
from pathlib import Path

from llm_panel import AGENT_DOC_CAP, agents

CACHE_VERSION = 1
CACHE_FILE_NAME = 'filenames.json'

READ_CAP = 200_000        # bytes read per file (same cap as the preview dialog)
SUMMARY_MAX_CHARS = 60    # a display name much longer than this stops being short
MTIME_EPS = 1e-6          # float mtime comparison tolerance

# Names that smell like secrets are never sent to the LLM, even when the user
# has "show hidden files" on (bulk-summarizing would otherwise ship .env-style
# files to the provider wholesale — the chat panel only sends files one
# explicit click at a time).
SENSITIVE_HINTS = ('.env', 'secret', 'credential', 'password', 'token',
                   'id_rsa', 'private_key')

PROMPT_TEMPLATE = (
    'You name files for a file browser. Below is the beginning of a file '
    'called "{name}". Reply with ONLY a short, human-readable display name '
    'for it — 2 to 6 words, at most {max_chars} characters — that describes '
    'what the file contains. No quotes, no file extension, no explanation, '
    'nothing else.\n\n'
    'File: {name}\n\n'
    '---\n{text}\n---\n\n'
    'Display name:'
)


def default_cache_dir() -> Path:
    return Path(os.environ.get('SHANGCENG_HOME') or Path.home() / '.shangceng') \
        .expanduser()


class SummaryStore:
    """absolute path → short AI display name, persisted as JSON on disk."""

    def __init__(self, root: Path | str | None = None):
        self.root = Path(root).expanduser() if root else default_cache_dir()
        self.file = self.root / CACHE_FILE_NAME
        self._lock = threading.Lock()
        self._summaries: dict[str, dict] = {}
        self.load()

    def load(self):
        try:
            data = json.loads(self.file.read_text('utf-8'))
            if data.get('version') == CACHE_VERSION and isinstance(data.get('summaries'), dict):
                self._summaries = data['summaries']
        except (OSError, ValueError, AttributeError):
            self._summaries = {}  # missing or corrupt cache — start fresh

    def save(self):
        """Write atomically (temp file + rename) so a crash can't corrupt it."""
        with self._lock:
            self.root.mkdir(parents=True, exist_ok=True)
            tmp = self.file.with_suffix('.json.tmp')
            tmp.write_text(json.dumps(
                {'version': CACHE_VERSION, 'summaries': self._summaries},
                ensure_ascii=False, indent=1), 'utf-8')
            tmp.replace(self.file)

    def get(self, path: Path | str, mtime: float, size: int) -> str | None:
        """The cached summary, unless the file changed since it was made."""
        rec = self._summaries.get(str(path))
        if rec and rec.get('size') == size \
                and abs(rec.get('mtime', 0) - mtime) < MTIME_EPS:
            return rec.get('summary')
        return None

    def put(self, path: Path | str, summary: str, mtime: float, size: int,
            provider: str = ''):
        self._summaries[str(path)] = {
            'summary': summary,
            'mtime': mtime,
            'size': size,
            'provider': provider,
            'created': dt.datetime.now().isoformat(timespec='seconds'),
        }

    def __len__(self):
        return len(self._summaries)


# The app keeps one shared cache across all browser tabs / page instances.
store = SummaryStore()


def is_sensitive(name: str) -> bool:
    lowered = name.lower()
    return any(hint in lowered for hint in SENSITIVE_HINTS)


def build_prompt(name: str, text: str) -> str:
    return PROMPT_TEMPLATE.format(name=name, text=text,
                                  max_chars=SUMMARY_MAX_CHARS)


def clean_summary(raw: str, max_chars: int = SUMMARY_MAX_CHARS) -> str:
    """First usable line of the reply, stripped of decoration; '' if none.

    Agent CLIs may interleave tool activity as ``🛠 …`` marker lines (the chat
    panel renders them; here they are simply dropped).
    """
    for line in (raw or '').splitlines():
        line = line.strip()
        if not line or line.startswith(('🛠', '#', '>', '-', '*', '—')):
            continue
        line = re.sub(r'^\d+[.)]\s*', '', line)      # "1. Budget notes"
        line = re.sub(r'\s+', ' ', line).strip('`"\' ')
        line = line.rstrip('.…')
        if not line:
            continue
        if len(line) > max_chars:
            line = line[:max_chars].rsplit(' ', 1)[0].strip()
        return line
    return ''


def collect_stream(gen) -> str:
    """Drain a chat-stream generator, dropping agent tool-marker lines."""
    text = ''.join(gen)
    return '\n'.join(l for l in text.splitlines()
                     if not l.lstrip().startswith('🛠'))


def make_stream_fn(chat):
    """Turn the chat panel's provider/model selection into a blocking
    ``(prompt) -> reply`` function (mirrors ChatPanel._make_stream_gen; the
    underscore reach-in for ``_resolve_model`` is deliberate — one source of
    truth for model resolution). Provider, model and per-run knobs are
    snapshotted at build time so mid-job UI changes can't mix combinations."""
    provider = chat.provider
    model, error = chat._resolve_model()
    if error:
        raise RuntimeError(error)
    variant = chat.opencode_variant.value or None if provider == 'OpenCode' else None
    thinking = chat.cline_thinking.value or None if provider == 'Cline' else None

    def stream_one(prompt: str) -> str:
        workdir = os.getcwd()
        if provider == 'OpenCode':
            gen = agents.opencode_chat_stream(prompt, model=model, workdir=workdir,
                                              variant=variant, hardened=False)
        elif provider == 'Cline':
            gen = agents.cline_chat_stream(prompt, model=model, workdir=workdir,
                                           thinking=thinking, hardened=False)
        else:  # ZCode: model routing is zcode's own config
            gen = agents.zcode_chat_stream(prompt, workdir=workdir, hardened=False)
        return collect_stream(gen)

    return stream_one


def summarize_file(path: Path | str, stream_fn) -> str | None:
    """Summarize one text file; None means nothing usable (never cached)."""
    try:
        with Path(path).open('rb') as f:  # read() caps even if the file grew
            raw = f.read(READ_CAP)
    except OSError:
        return None
    text = raw.decode('utf-8', 'replace')
    if not text.strip():
        return None
    prompt = build_prompt(Path(path).name, text[:AGENT_DOC_CAP])
    return clean_summary(stream_fn(prompt)) or None
